### ISSUE TITLE
Add support for LS_COLORS through vivid

### ISSUE THREAD

**Issue by orhanbalci** [shuhei/colortty#10]
Another nice to have functionality for this tool might be
generating LS_COLORS colors compatible with theme. I personally use [vivid](https://github.com/sharkdp/vivid) for this. Generating vivid [color theme](https://github.com/sharkdp/vivid/tree/master/themes) file compatible with selected theme would be lovely. It is annoying when ls_colors settings and your terminal colors do not match.

**Comment by shuhei** [comment]
I'm not familiar with `LS_COLORS` or details of terminal colors, but it seems that the theme files of vivid have arbitrary color names in `colors`. So, I'm not sure how to map alacritty colors to the colors in `LS_COLORS`.

One possible way to match colors of alacritty and `LS_COLORS` would be to use the 16 colors instead of exact color codes in `LS_COLORS`. Then, alacritty will render the 16 colors with its color scheme.

**Comment by orhanbalci** [comment]
Actually as far as  i know there is not a one to one mapping between terminal colors and LS_COLORS. May be we can look at a well known terminal color theme and vivid configuration and find a mapping. 
Monokai is a good example of this.

**Comment by shuhei** [comment]
I checked vivid themes and read about LS_COLORS. If we want to create LS_COLORS that match with Alacritty color theme, we need two information.

1. pick colors for file types (for example, make executable red)
2. use the exact colors from Alacritty color theme

2) can be automatically achieved if LS_COLORS uses [3/4 bit colors](https://en.m.wikipedia.org/wiki/ANSI_escape_code#Colors). We can't automatically generate 1) for arbitrary color schemes. You can use an OS default LS_COLORS that uses 3/4-bit colors or create one with more file types.

I'm closing this issue because I think it's out of the scope of converting Alacrtty color schemes.
